#!/bin/bash

set -o errexit -o nounset -o pipefail
set -o xtrace

# Straightforward and ugly for now: run the `spectre_v1_pht_sa` demo as a test
# by looking for it anywhere we might have built it.

[[ -x ./build/demos/spectre_v1_pht_sa ]] &&
    ./build/demos/spectre_v1_pht_sa
[[ -x ./build-x86_64/demos/spectre_v1_pht_sa ]] &&
    ./build-x86_64/demos/spectre_v1_pht_sa
[[ -x ./build-i686/demos/spectre_v1_pht_sa ]] &&
    ./build-i686/demos/spectre_v1_pht_sa
[[ -x ./build-win32/demos/Debug/spectre_v1_pht_sa.exe ]] &&
    ./build-win32/demos/Debug/spectre_v1_pht_sa.exe
[[ -x ./build-x64/demos/Debug/spectre_v1_pht_sa.exe ]] &&
    ./build-x64/demos/Debug/spectre_v1_pht_sa.exe

# Avoid a nonzero exit code. Otherwise we'll return the exit code of our last
# command, which is often an unsatisfied [[ -x ... ]] condition.
true
